name: test

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pytest
        pip install -r requirements.txt
        pip install -e .
    - name: Unit testing
      run: |
        pytest
